package com.medinaparra.freecadandroid.viewer

import android.opengl.GLES30
import android.opengl.GLSurfaceView
import android.opengl.Matrix
import android.util.Log
import com.medinaparra.freecadandroid.model.SceneMesh
import java.nio.ByteBuffer
import java.nio.ByteOrder
import javax.microedition.khronos.egl.EGLConfig
import javax.microedition.khronos.opengles.GL10

/** OpenGL ES 3 renderer for meshes generated by OCCT. */
class CadRenderer : GLSurfaceView.Renderer {
    val cameraController = CameraController()

    @Volatile
    private var pendingMesh: SceneMesh? = null
    private var activeMesh: SceneMesh? = null
    private var uploadPending = false

    private var meshProgram = 0
    private var axesProgram = 0
    private var meshVbo = 0
    private var meshIbo = 0
    private var axesVbo = 0
    private var indexCount = 0
    private var viewportWidth = 1
    private var viewportHeight = 1

    private val modelMatrix = FloatArray(16)
    private val viewMatrix = FloatArray(16)
    private val projectionMatrix = FloatArray(16)
    private val modelViewMatrix = FloatArray(16)
    private val mvpMatrix = FloatArray(16)

    private var meshMvpLocation = -1
    private var meshModelLocation = -1
    private var meshColorLocation = -1
    private var meshLightLocation = -1
    private var axesMvpLocation = -1

    fun setMesh(mesh: SceneMesh) {
        synchronized(this) {
            pendingMesh = mesh
            uploadPending = true
        }
    }

    override fun onSurfaceCreated(gl: GL10?, config: EGLConfig?) {
        GLES30.glClearColor(0.055f, 0.055f, 0.065f, 1f)
        GLES30.glEnable(GLES30.GL_DEPTH_TEST)
        GLES30.glEnable(GLES30.GL_CULL_FACE)
        GLES30.glCullFace(GLES30.GL_BACK)

        meshProgram = createProgram(MESH_VERTEX_SHADER, MESH_FRAGMENT_SHADER)
        axesProgram = createProgram(AXES_VERTEX_SHADER, AXES_FRAGMENT_SHADER)

        meshMvpLocation = GLES30.glGetUniformLocation(meshProgram, "uMvp")
        meshModelLocation = GLES30.glGetUniformLocation(meshProgram, "uModel")
        meshColorLocation = GLES30.glGetUniformLocation(meshProgram, "uColor")
        meshLightLocation = GLES30.glGetUniformLocation(meshProgram, "uLightDirection")
        axesMvpLocation = GLES30.glGetUniformLocation(axesProgram, "uMvp")

        val buffers = IntArray(3)
        GLES30.glGenBuffers(3, buffers, 0)
        meshVbo = buffers[0]
        meshIbo = buffers[1]
        axesVbo = buffers[2]
        uploadAxes()

        // A context recreation invalidates GPU buffers, so upload the active mesh again.
        synchronized(this) {
            activeMesh?.let {
                pendingMesh = it
                uploadPending = true
            }
        }
    }

    override fun onSurfaceChanged(gl: GL10?, width: Int, height: Int) {
        viewportWidth = width.coerceAtLeast(1)
        viewportHeight = height.coerceAtLeast(1)
        GLES30.glViewport(0, 0, viewportWidth, viewportHeight)
    }

    override fun onDrawFrame(gl: GL10?) {
        GLES30.glClear(GLES30.GL_COLOR_BUFFER_BIT or GLES30.GL_DEPTH_BUFFER_BIT)

        val meshToUpload = synchronized(this) {
            if (uploadPending) {
                uploadPending = false
                pendingMesh
            } else {
                null
            }
        }
        meshToUpload?.let(::uploadMesh)

        Matrix.setIdentityM(modelMatrix, 0)
        cameraController.getViewMatrix(viewMatrix)
        cameraController.getProjectionMatrix(projectionMatrix, viewportWidth, viewportHeight)
        Matrix.multiplyMM(modelViewMatrix, 0, viewMatrix, 0, modelMatrix, 0)
        Matrix.multiplyMM(mvpMatrix, 0, projectionMatrix, 0, modelViewMatrix, 0)

        drawAxes()
        if (indexCount > 0) drawMesh()
    }

    private fun uploadMesh(mesh: SceneMesh) {
        activeMesh = mesh
        indexCount = mesh.indices.size

        val vertexBuffer = ByteBuffer
            .allocateDirect(mesh.vertices.size * Float.SIZE_BYTES)
            .order(ByteOrder.nativeOrder())
            .asFloatBuffer()
            .apply {
                put(mesh.vertices)
                position(0)
            }
        val indexBuffer = ByteBuffer
            .allocateDirect(mesh.indices.size * Int.SIZE_BYTES)
            .order(ByteOrder.nativeOrder())
            .asIntBuffer()
            .apply {
                put(mesh.indices)
                position(0)
            }

        GLES30.glBindBuffer(GLES30.GL_ARRAY_BUFFER, meshVbo)
        GLES30.glBufferData(
            GLES30.GL_ARRAY_BUFFER,
            mesh.vertices.size * Float.SIZE_BYTES,
            vertexBuffer,
            GLES30.GL_STATIC_DRAW
        )

        GLES30.glBindBuffer(GLES30.GL_ELEMENT_ARRAY_BUFFER, meshIbo)
        GLES30.glBufferData(
            GLES30.GL_ELEMENT_ARRAY_BUFFER,
            mesh.indices.size * Int.SIZE_BYTES,
            indexBuffer,
            GLES30.GL_STATIC_DRAW
        )
        GLES30.glBindBuffer(GLES30.GL_ARRAY_BUFFER, 0)
        GLES30.glBindBuffer(GLES30.GL_ELEMENT_ARRAY_BUFFER, 0)
    }

    private fun uploadAxes() {
        val length = 1.5f
        val axes = floatArrayOf(
            0f, 0f, 0f, 1f, 0f, 0f, length, 0f, 0f, 1f, 0f, 0f,
            0f, 0f, 0f, 0f, 1f, 0f, 0f, length, 0f, 0f, 1f, 0f,
            0f, 0f, 0f, 0f, 0f, 1f, 0f, 0f, length, 0f, 0f, 1f
        )
        val buffer = ByteBuffer
            .allocateDirect(axes.size * Float.SIZE_BYTES)
            .order(ByteOrder.nativeOrder())
            .asFloatBuffer()
            .apply {
                put(axes)
                position(0)
            }
        GLES30.glBindBuffer(GLES30.GL_ARRAY_BUFFER, axesVbo)
        GLES30.glBufferData(
            GLES30.GL_ARRAY_BUFFER,
            axes.size * Float.SIZE_BYTES,
            buffer,
            GLES30.GL_STATIC_DRAW
        )
        GLES30.glBindBuffer(GLES30.GL_ARRAY_BUFFER, 0)
    }

    private fun drawMesh() {
        GLES30.glUseProgram(meshProgram)
        GLES30.glUniformMatrix4fv(meshMvpLocation, 1, false, mvpMatrix, 0)
        GLES30.glUniformMatrix4fv(meshModelLocation, 1, false, modelMatrix, 0)
        GLES30.glUniform4f(meshColorLocation, 0.18f, 0.57f, 0.82f, 1f)
        GLES30.glUniform3f(meshLightLocation, 0.4f, 0.7f, 1f)

        GLES30.glBindBuffer(GLES30.GL_ARRAY_BUFFER, meshVbo)
        GLES30.glEnableVertexAttribArray(0)
        GLES30.glVertexAttribPointer(
            0,
            3,
            GLES30.GL_FLOAT,
            false,
            SceneMesh.VERTEX_STRIDE_BYTES,
            0
        )
        GLES30.glEnableVertexAttribArray(1)
        GLES30.glVertexAttribPointer(
            1,
            3,
            GLES30.GL_FLOAT,
            false,
            SceneMesh.VERTEX_STRIDE_BYTES,
            3 * Float.SIZE_BYTES
        )

        GLES30.glBindBuffer(GLES30.GL_ELEMENT_ARRAY_BUFFER, meshIbo)
        GLES30.glDrawElements(GLES30.GL_TRIANGLES, indexCount, GLES30.GL_UNSIGNED_INT, 0)

        GLES30.glDisableVertexAttribArray(0)
        GLES30.glDisableVertexAttribArray(1)
        GLES30.glBindBuffer(GLES30.GL_ARRAY_BUFFER, 0)
        GLES30.glBindBuffer(GLES30.GL_ELEMENT_ARRAY_BUFFER, 0)
    }

    private fun drawAxes() {
        GLES30.glUseProgram(axesProgram)
        GLES30.glUniformMatrix4fv(axesMvpLocation, 1, false, mvpMatrix, 0)
        GLES30.glBindBuffer(GLES30.GL_ARRAY_BUFFER, axesVbo)
        GLES30.glEnableVertexAttribArray(0)
        GLES30.glVertexAttribPointer(0, 3, GLES30.GL_FLOAT, false, 24, 0)
        GLES30.glEnableVertexAttribArray(1)
        GLES30.glVertexAttribPointer(1, 3, GLES30.GL_FLOAT, false, 24, 12)
        GLES30.glLineWidth(3f)
        GLES30.glDrawArrays(GLES30.GL_LINES, 0, 6)
        GLES30.glDisableVertexAttribArray(0)
        GLES30.glDisableVertexAttribArray(1)
        GLES30.glBindBuffer(GLES30.GL_ARRAY_BUFFER, 0)
    }

    fun releaseBuffers() {
        if (meshVbo != 0 || meshIbo != 0 || axesVbo != 0) {
            GLES30.glDeleteBuffers(3, intArrayOf(meshVbo, meshIbo, axesVbo), 0)
        }
        if (meshProgram != 0) GLES30.glDeleteProgram(meshProgram)
        if (axesProgram != 0) GLES30.glDeleteProgram(axesProgram)
        meshVbo = 0
        meshIbo = 0
        axesVbo = 0
        meshProgram = 0
        axesProgram = 0
        indexCount = 0
    }

    private fun createProgram(vertexSource: String, fragmentSource: String): Int {
        val vertexShader = compileShader(GLES30.GL_VERTEX_SHADER, vertexSource)
        val fragmentShader = compileShader(GLES30.GL_FRAGMENT_SHADER, fragmentSource)
        val program = GLES30.glCreateProgram()
        GLES30.glAttachShader(program, vertexShader)
        GLES30.glAttachShader(program, fragmentShader)
        GLES30.glLinkProgram(program)

        val status = IntArray(1)
        GLES30.glGetProgramiv(program, GLES30.GL_LINK_STATUS, status, 0)
        val log = GLES30.glGetProgramInfoLog(program)
        GLES30.glDeleteShader(vertexShader)
        GLES30.glDeleteShader(fragmentShader)
        check(status[0] == GLES30.GL_TRUE) { "OpenGL program link failed: $log" }
        return program
    }

    private fun compileShader(type: Int, source: String): Int {
        val shader = GLES30.glCreateShader(type)
        GLES30.glShaderSource(shader, source)
        GLES30.glCompileShader(shader)
        val status = IntArray(1)
        GLES30.glGetShaderiv(shader, GLES30.GL_COMPILE_STATUS, status, 0)
        if (status[0] != GLES30.GL_TRUE) {
            val log = GLES30.glGetShaderInfoLog(shader)
            GLES30.glDeleteShader(shader)
            Log.e(TAG, log)
            error("OpenGL shader compilation failed: $log")
        }
        return shader
    }

    private companion object {
        const val TAG = "CadRenderer"

        val MESH_VERTEX_SHADER = """
            #version 300 es
            uniform mat4 uMvp;
            uniform mat4 uModel;
            layout(location = 0) in vec3 aPosition;
            layout(location = 1) in vec3 aNormal;
            out vec3 vNormal;
            void main() {
                vNormal = normalize(mat3(uModel) * aNormal);
                gl_Position = uMvp * vec4(aPosition, 1.0);
            }
        """.trimIndent()

        val MESH_FRAGMENT_SHADER = """
            #version 300 es
            precision mediump float;
            uniform vec4 uColor;
            uniform vec3 uLightDirection;
            in vec3 vNormal;
            out vec4 fragmentColor;
            void main() {
                vec3 normal = normalize(vNormal);
                float diffuse = max(dot(normal, normalize(uLightDirection)), 0.0);
                float lighting = 0.28 + diffuse * 0.72;
                fragmentColor = vec4(uColor.rgb * lighting, uColor.a);
            }
        """.trimIndent()

        val AXES_VERTEX_SHADER = """
            #version 300 es
            uniform mat4 uMvp;
            layout(location = 0) in vec3 aPosition;
            layout(location = 1) in vec3 aColor;
            out vec3 vColor;
            void main() {
                vColor = aColor;
                gl_Position = uMvp * vec4(aPosition, 1.0);
            }
        """.trimIndent()

        val AXES_FRAGMENT_SHADER = """
            #version 300 es
            precision mediump float;
            in vec3 vColor;
            out vec4 fragmentColor;
            void main() {
                fragmentColor = vec4(vColor, 1.0);
            }
        """.trimIndent()
    }
}
